//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalAddressBook.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Data {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Data() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PersonalAddressBook.Resources.Data", typeof(Data).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First_Name,Last_Name,Address,Cty-State-Zipcode,Phone_Number
        ///Arturo,Wisniewski,19804 Beilfuss Point,Bordeaux,252.235.129.186
        ///Jordan,Richardt,259 Mccormick Avenue,Kamenskiy,78.129.249.201
        ///Darline,MacDonough,47210 Green Ridge Plaza,Vukatanë,91.75.130.61
        ///Temp,Cushe,5 Killdeer Terrace,Lubāna,77.78.83.123
        ///Manda,Saunderson,5288 Sycamore Park,Kamenný Přívoz,54.98.152.234
        ///Herb,Turpin,3 Lukken Center,Sanbao,170.199.31.33
        ///Timmy,Kitto,456 Reindahl Park,Botao,153.18.211.194
        ///Rawley,Broe,9 Tennessee Park,Tak,225.127.187.1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MOCK_DATA {
            get {
                return ResourceManager.GetString("MOCK_DATA", resourceCulture);
            }
        }
    }
}
